### ISSUE TITLE
Python Command Line Arguments -- Implementation

### ISSUE THREAD

**Issue by nikkolas-james-irwin** [nikkolas-james-irwin/big-data-systems-course-project#26]
- Ideally, with Brianna's help (@bblain18) from her previous project, we can implement command-line arguments for CARS that will allow for a variety of customizations.
- Currently, there is not a specified list of arguments to be implemented for this issue.
- Suggestions should be placed as new comments under this issue, discussed in Slack, over Zoom, or whatever communication medium is the most ideal and then documented here for the rest of the team.
- Some initial examples of useful command-line arguments would be the following:
    - The ability to specify the dataset file to run, **-f**
    - The ability to save the results to a log file, **-l**
    - The ability to turn on/off data visualizations, **-s**
    - The ability to specify the logical core count for the Spark Context, **-c**
    - The ability to run the application without the Spark Application UI (web browser), **-o**
- Implemented commands should be added to the README file

**Comment by bblain18** [comment]
Add -n for number for rows output.

**Comment by bblain18** [comment]
- v, --verbose Added but does not have functionality
--version Added to display version number
-o has been updated to be the ability to run the application with the Spark Application UI (web browser)

**Comment by nikkolas-james-irwin** [comment]
Add -a to display information about the program

- This command-line option should provide an output at the beginning of the program execution **before any other output** and it should display attribution both for our team and from the original jupyter/minimal-notebook that was used.

**Comment by bblain18** [comment]
- -p, --predictions Added with functionality to set number of predictions to be calculated

**Comment by nikkolas-james-irwin** [comment]
This has been resolved by multiple pull requests. Closing this issue.
